#pragma once

/*
 * LEFT HALF
 *   COL0..COL7 = GP0..GP7
 *   ROW0..ROW5 = GP8..GP13
 *
 * RIGHT HALF
 *   ROW0..ROW5 = GP5,GP4,GP3,GP2,GP1,GP0
 *   COL0..COL8 = GP14,GP13,GP12,GP11,GP10,GP9,GP8,GP7,GP6
 *
 * BOTH HALVES
 *   split TX = GP16
 *   split RX = GP17
 *   OLED SDA = GP18
 *   OLED SCL = GP19
 *   encoder A = GP20
 *   encoder B = GP21
 */

#define MATRIX_ROWS 12
#define MATRIX_COLS 9


#define DIODE_DIRECTION COL2ROW

#define MATRIX_ROW_PINS { GP8, GP9, GP10, GP11, GP12, GP13 }
#define MATRIX_COL_PINS { GP0, GP1, GP2, GP3, GP4, GP5, GP6, GP7, NO_PIN }

#define MATRIX_ROW_PINS_RIGHT { GP5, GP4, GP3, GP2, GP1, GP0 }
#define MATRIX_COL_PINS_RIGHT { GP14, GP13, GP12, GP11, GP10, GP9, GP8, GP7, GP6 }


#define EE_HANDS

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP16
#define SERIAL_USART_RX_PIN GP17

#define SPLIT_USB_DETECT
#define SPLIT_WATCHDOG_ENABLE
#define SPLIT_WATCHDOG_TIMEOUT 3000

#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define SPLIT_WPM_ENABLE
#define SPLIT_OLED_ENABLE
#define SPLIT_ACTIVITY_ENABLE

#define ENCODER_A_PINS { GP20 }
#define ENCODER_B_PINS { GP21 }
#define ENCODER_A_PINS_RIGHT { GP20 }
#define ENCODER_B_PINS_RIGHT { GP21 }
#define ENCODER_RESOLUTION 4

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP18
#define I2C1_SCL_PIN GP19
#define OLED_DISPLAY_ADDRESS 0x3C
#define OLED_BRIGHTNESS 128
#define OLED_TIMEOUT 60000

/* Useful on a Pico during early testing. */
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U

#define DEBOUNCE 5
