
MCU = RP2040
BOARD = GENERIC_RP_RP2040
BOOTLOADER = rp2040

SPLIT_KEYBOARD = yes

SERIAL_DRIVER = vendor

ENCODER_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
OLED_TRANSPORT = i2c

LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
AUDIO_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
